name: Build and Deploy to DockerHub

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & Push Laravel app image
      - name: Build and Push Laravel Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/statamic-app:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/statamic-app:latest

      # Build & Push MinIO custom image
      - name: Build and Push MinIO Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfile.minio
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/statamic-minio:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/statamic-minio:latest